version: '3.8'

services:
  redis:
    image: valkey/valkey:7.2
    ports:
      - 6379:6379
    stop_grace_period: 60s
    restart: always


networks:
  default:
    name: redis-streams
    driver: bridge